# build steve's dev environment docker image
FROM artifactory.scitec.com/mdpap/pipeline-rhel-8-tier-1m
#FROM artifactory.scitec.com/mdpap/base-images/tier-2/mdpap-cicd

ARG HOME
ARG UID
ARG GID
ARG NAME

ENTRYPOINT ["bash", "--login"]

# mount subscription
RUN --mount=type=secret,id=artifactory_username \
    --mount=type=secret,id=artifactory_token \
  dnf config-manager --add-repo \
    "https://$(cat /run/secrets/artifactory_username):$(cat /run/secrets/artifactory_token)@artifactory.scitec.com/artifactory/mdpap-virtual-rpm" \
  && dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

RUN dnf install -y vim jq htop sudo ShellCheck nano bash-completion java-latest-openjdk-devel maven \
  && dnf remove -y podman \
  && groupadd docker -g 972 \
  && dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo \
  && dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin \
  && dnf clean all \
  && rm -rf /var/cache/yum \
  && rm -rf /var/cache/dnf 

# make the compiler work
RUN ln -s /usr/local/gcc-trunk/bin/gcc /usr/bin/cc \
  && ln -s /usr/local/gcc-trunk/bin/g++ /usr/bin/c++

# Add a user and a group. We don't give the user the AD ids because they are >1B and that causes the docker image to 
# balloon to over 361GB is size. Something about a sparse file becomig non-sparse in Docker? I have lost the 
# reference. Anyway, so the hack here is to re-write the UID and GID after the fact, and keeps that file small.
RUN groupadd devs \
    && useradd --home-dir "${HOME}" "${NAME}" \
    && sed -i -r -e "/${NAME}/ s/x:1000/x:${UID}/" /etc/passwd \
    && sed -i -r -e "s/:1001:/:${GID}:/" /etc/passwd \
    && sed -i -r -e "/${NAME}/ s/:1001:/:${GID}:/" /etc/group \
    && usermod -aG docker,wheel,devs "${NAME}"

RUN sed -i -r -e "s/^%/#%/" /etc/sudoers \
    && echo '%wheel  ALL=(ALL)  NOPASSWD: ALL' >> /etc/sudoers

WORKDIR  "${HOME}"
USER     "${NAME}"

