#!/usr/bin/env bash
set -e

SCRIPT_DIR=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))
BUILD_IMAGE=Dockerfile-rpm
IMAGE=srb-rpm
CONTAINER_NAME=rpm

if docker ps -a | grep "${CONTAINER_NAME}" > /dev/null
then
  docker exec -it \
    --workdir "${PWD}" \
    --user "$(id -un):$(id -un)" \
    "${CONTAINER_NAME}" \
    bash

else
  if [[ -n "${BUILD_IMAGE}" ]]
  then
    docker build \
      -f "${SCRIPT_DIR}/${BUILD_IMAGE}" \
      --build-arg "BASE_IMAGE=${BUILD_IMAGE}" \
      --build-arg "HOME=${HOME}" \
      --build-arg "NAME=$(id -un)" \
      --build-arg "UID=$(id -u)" \
      --build-arg "GID=$(id -g)" \
      --secret id=artifactory_username,src=${HOME}/secrets/arti-user \
      --secret id=artifactory_token,src=${HOME}/secrets/arti-token \
      -t "${IMAGE}" "${SCRIPT_DIR}"
  fi

  docker run -it --rm \
    --name "${CONTAINER_NAME}" \
    --hostname "${CONTAINER_NAME}" \
    --workdir ${PWD} \
    --user "$(id -un):$(id -un)" \
    --group-add "wheel" \
    --group-add "devs" \
    -v "${HOME}:${HOME}" \
    -v "/opt/scitec:/opt/scitec" \
    -v "/var/run/docker.sock:/var/run/docker.sock" \
    ${IMAGE}
fi
